// @jfs/pwa-kit v0.2.0 — shared service-worker primitives for the JFS family of
// buildless static PWAs.
//
// Every sibling app (Weather, FlightCheck, Art-Gallery, market-monitor,
// JFS-Sports) hand-rolls the same service worker: a version-keyed cache name,
// an app-shell precache list, install/activate/old-cache eviction, and some mix
// of network-first / cache-first / stale-while-revalidate / timeout-raced
// fetch strategies. Each one re-derives that logic slightly differently, and
// the family's #1 recurring bug — returning visitors stuck on a stale cached
// shell because someone forgot to bump the version — lives right here. This
// module is the single, tested copy of that logic.
//
// Pure ESM, dependency-free. Two layers:
//   1. Composable PRIMITIVES — lifecycle helpers (precache, pruneCaches,
//      claimClients, notifyClients, onSkipWaiting), predicates/helpers
//      (makeCacheable, safeCachePut, trimCache, offlineResponse,
//      stripQueryParams), and strategy functions (cacheFirst, networkFirst,
//      staleWhileRevalidate, networkFirstWithTimeout). Apps with bespoke
//      routing compose these in a slim sw.js.
//   2. createServiceWorker(config) — a declarative one-call factory for the
//      simple "one shell, one strategy" case, built on the primitives above.
//
// v0.2.0 is a backward-compatible superset of v0.1.0 (the createServiceWorker
// factory + its pure helpers are unchanged in behavior).
//
// Because a classic service worker can't `import` an ESM module, each app
// vendors a classic-global build of this file (generated by
// scripts/vendor-pwa-kit.mjs, exposing `self.PWAKit`) and loads it with
// `importScripts(...)`. Tests import this ESM source directly.

// ───────────────────────── pure helpers ─────────────────────────

/** Build the versioned cache name. Keeping the version in the key is what makes
 *  an old deploy's cache get evicted on activate — bump the version, get a
 *  clean cache. */
export function cacheName(prefix, version) {
  return `${prefix}-${version}`;
}

/** Resolve a shell list (which may contain relative paths like './' or
 *  'css/style.css') to a Set of absolute pathnames, against the SW's own
 *  location. */
export function resolveShellPaths(shell, base) {
  return new Set(shell.map((p) => new URL(p, base).pathname));
}

/** Given the existing CacheStorage keys, return the ones to delete on activate.
 *  `keep` may be a single name, or an array/Set of names to retain (apps with
 *  several buckets — shell/runtime/api, or shell + an unversioned image cache).
 *  With `prefix`, only keys with that prefix are eligible for pruning, so
 *  co-hosted apps on the same origin don't wipe each other. */
export function staleCacheKeys(keys, keep, prefix) {
  const keepSet = keep instanceof Set ? keep : new Set(Array.isArray(keep) ? keep : [keep]);
  return keys.filter((k) => !keepSet.has(k) && (prefix ? k.startsWith(prefix) : true));
}

/** Build a response-cacheability predicate.
 *    allowOpaque      — accept opaque cross-origin responses (status 0). Needed
 *                       for no-cors images; off by default since an opaque body
 *                       can't be inspected for staleness.
 *    requireBasic     — only same-origin ('basic') responses.
 *    allowRedirected  — when false, reject res.redirected (can't trust the URL).
 *    status           — require an exact status (e.g. 200), excluding other 2xx.
 *  The default predicate is simply `res.ok`. */
export function makeCacheable(opts = {}) {
  const { allowOpaque = false, requireBasic = false, allowRedirected = true, status = null } = opts;
  return (res) => {
    if (!res) return false;
    if (res.type === 'opaque') return allowOpaque;
    if (!res.ok) return false;
    if (requireBasic && res.type !== 'basic') return false;
    if (!allowRedirected && res.redirected) return false;
    if (status != null && res.status !== status) return false;
    return true;
  };
}
const defaultCacheable = (res) => !!res && res.ok;

/** cache.put can reject when the origin's storage quota is exhausted. These are
 *  best-effort background writes, so swallow the failure rather than leak an
 *  unhandled rejection. */
export function safeCachePut(cache, request, response) {
  return cache.put(request, response).catch(() => {});
}

/** FIFO eviction: Cache.keys() returns entries in insertion order, so deleting
 *  from the front drops the least-recently-added entries first. Cheap and good
 *  enough for an immutable-asset cache (e.g. museum images) — no LRU bookkeeping. */
export async function trimCache(cache, max) {
  const keys = await cache.keys();
  if (keys.length <= max) return;
  for (let i = 0; i < keys.length - max; i++) {
    await cache.delete(keys[i]).catch(() => {});
  }
}

/** A deterministic offline fallback Response (default: 503 text/html) for when
 *  both network and cache miss, so respondWith never resolves to undefined. */
export function offlineResponse(body, init = {}) {
  return new Response(body, {
    status: init.status || 503,
    statusText: init.statusText || 'Service Unavailable',
    headers: init.headers || { 'Content-Type': 'text/html; charset=utf-8' },
  });
}

/** Return a request with the given query params stripped, for a stable cache
 *  key (e.g. dropping a `?cb=<timestamp>` buster). The outbound request is
 *  untouched — only the key used for cache lookup/write changes. Falls back to
 *  the original request if a Request can't be reconstructed. */
export function stripQueryParams(request, params, RequestCtor) {
  let url;
  try { url = new URL(request.url); } catch { return request; }
  let changed = false;
  for (const p of params) {
    if (url.searchParams.has(p)) { url.searchParams.delete(p); changed = true; }
  }
  if (!changed) return request;
  const Ctor = RequestCtor || (typeof Request !== 'undefined' ? Request : null);
  if (!Ctor) return request;
  try {
    return new Ctor(url.toString(), { method: request.method, headers: request.headers });
  } catch {
    return request;
  }
}

/** Decide how a GET should be handled: 'bypass' | 'cdn' | 'shell'. See the
 *  config knobs on createServiceWorker. */
export function routeRequest(url, request, config) {
  const cdnHosts = config.cdnHosts instanceof Set
    ? config.cdnHosts
    : new Set(config.cdnHosts || []);
  if (config.bypassPrefixes && config.bypassPrefixes.some((p) => url.pathname.startsWith(p))) {
    return 'bypass';
  }
  if (cdnHosts.has(url.hostname)) return 'cdn';
  if (url.origin !== config.origin) return 'bypass';
  const navigate = request && request.mode === 'navigate';
  const exts = config.shellExtensions;
  if (exts && exts.length) {
    if (navigate || exts.some((e) => url.pathname.endsWith(e))) return 'shell';
    return 'bypass';
  }
  return 'shell';
}

/** Decide whether a successful shell response may enter the cache.
 *    'listed'      — only paths in the precache shell set (bounded cache).
 *    'shellRouted' — any same-origin ('basic') ok response routed as shell. */
export function shouldCacheResponse(url, response, mode, shellPathSet) {
  if (!response || !response.ok) return false;
  if (mode === 'listed') return shellPathSet.has(url.pathname);
  return response.type === 'basic';
}

// ───────────────────────── lifecycle primitives ─────────────────────────

/** Precache a shell list into `cacheName`.
 *    mode 'all-or-nothing' — cache.addAll: a single 404 aborts install (use
 *                            when a broken shell should fail the install).
 *    mode 'best-effort'    — individual adds via allSettled: whatever resolves
 *                            is cached, a stray miss just isn't available offline.
 *  `requestInit` (e.g. { cache: 'reload' }) bypasses the HTTP cache so a freshly
 *  bumped build never pre-caches the previous version's bytes. */
export async function precache(scope, name, assets, opts = {}) {
  const { mode = 'all-or-nothing', requestInit } = opts;
  const cache = await scope.caches.open(name);
  const list = assets || [];
  const req = (u) => (requestInit ? new Request(u, requestInit) : u);
  if (mode === 'best-effort') {
    await Promise.allSettled(list.map((u) => cache.add(req(u))));
  } else {
    await cache.addAll(list.map(req));
  }
}

/** Delete stale caches on activate. `keep` is a name or array/Set of names. */
export async function pruneCaches(scope, keep, prefix) {
  const keys = await scope.caches.keys();
  await Promise.all(staleCacheKeys(keys, keep, prefix).map((k) => scope.caches.delete(k)));
}

/** Take control of already-open pages. NOTE: some apps deliberately skip this
 *  (Art-Gallery) because claiming fires controllerchange and, paired with a
 *  reload-on-controllerchange, can loop on iOS Safari — only call it when the
 *  app wants the new worker to control the current page immediately. */
export async function claimClients(scope) {
  await scope.clients.claim();
}

/** Post a message (e.g. { type: 'SW_UPDATED' }) to controlled clients. */
export async function notifyClients(scope, message, matchOptions) {
  const clients = await scope.clients.matchAll(matchOptions || { type: 'window', includeUncontrolled: true });
  for (const c of clients) c.postMessage(message);
}

/** Wire a `message` listener that calls skipWaiting() when the page posts
 *  { type } (default 'SKIP_WAITING') — lets the page nudge a waiting worker
 *  into immediate activation after a deploy. */
export function onSkipWaiting(scope, type = 'SKIP_WAITING') {
  scope.addEventListener('message', (event) => {
    if (event.data && event.data.type === type) scope.skipWaiting();
  });
}

// ───────────────────────── strategy primitives ─────────────────────────
//
// Each strategy takes (request, ctx). ctx:
//   scope        — the SW global (provides caches, fetch, setTimeout)
//   cacheName    — bucket to read/write
//   isCacheable  — predicate (default res.ok); build with makeCacheable()
//   cacheKey     — key to read/write under (default: request) — for stripped keys
//   matchOptions — CacheQueryOptions for lookups (e.g. { ignoreSearch: true })
//   fallback     — () => Response used when network+cache both miss
//   timeoutMs    — (networkFirstWithTimeout only) ms before falling back to cache

/** Serve from cache, hit the network only on a miss. For immutable, versioned
 *  shell assets. */
export async function cacheFirst(request, ctx) {
  const cache = await ctx.scope.caches.open(ctx.cacheName);
  const key = ctx.cacheKey || request;
  const cached = await cache.match(key, ctx.matchOptions);
  if (cached) return cached;
  const res = await ctx.scope.fetch(request);
  if ((ctx.isCacheable || defaultCacheable)(res)) safeCachePut(cache, key, res.clone());
  return res;
}

/** Fetch fresh, fall back to cache (then optional offline fallback). For assets
 *  that carry shipped changes — always pick up the latest deploy when online. */
export async function networkFirst(request, ctx) {
  const cache = await ctx.scope.caches.open(ctx.cacheName);
  const key = ctx.cacheKey || request;
  try {
    const res = await ctx.scope.fetch(request);
    if ((ctx.isCacheable || defaultCacheable)(res)) safeCachePut(cache, key, res.clone());
    return res;
  } catch (err) {
    const cached = await cache.match(key, ctx.matchOptions);
    if (cached) return cached;
    if (ctx.fallback) return ctx.fallback();
    throw err;
  }
}

/** Serve the cached copy immediately and refresh it in the background, so the
 *  *next* load is current. For data that changes out-of-band and doesn't ride
 *  the app's version bump. */
export async function staleWhileRevalidate(request, ctx) {
  const cache = await ctx.scope.caches.open(ctx.cacheName);
  const key = ctx.cacheKey || request;
  const cached = await cache.match(key, ctx.matchOptions);
  const revalidate = ctx.scope.fetch(request).then((res) => {
    if ((ctx.isCacheable || defaultCacheable)(res)) safeCachePut(cache, key, res.clone());
    return res;
  });
  if (cached) {
    revalidate.catch(() => {}); // background refresh; ignore offline failures
    return cached;
  }
  return ctx.fallback ? revalidate.catch(() => ctx.fallback()) : revalidate;
}

/** Network-first, but if the network hasn't replied within `timeoutMs`, fall
 *  back to the last cached copy while the network fetch keeps running and
 *  refreshes the cache for the next tick. A pre-timeout 5xx also prefers a good
 *  cached copy over surfacing a transient server error. */
export async function networkFirstWithTimeout(request, ctx) {
  const cache = await ctx.scope.caches.open(ctx.cacheName);
  const key = ctx.cacheKey || request;
  const isCacheable = ctx.isCacheable || defaultCacheable;
  let settled = false;

  const network = ctx.scope.fetch(request).then(async (resp) => {
    settled = true;
    if (isCacheable(resp)) { try { await cache.put(key, resp.clone()); } catch { /* quota */ } }
    return resp;
  });

  const timed = new Promise((resolve) => {
    ctx.scope.setTimeout(async () => {
      if (settled) return;
      const cached = await cache.match(key, ctx.matchOptions);
      if (cached) resolve(cached);
    }, ctx.timeoutMs);
  });

  try {
    const raced = (await Promise.race([network, timed])) || network;
    if (raced && raced.status >= 500) {
      const cached = await cache.match(key, ctx.matchOptions);
      if (cached) return cached;
    }
    return raced;
  } catch (e) {
    const cached = await cache.match(key, ctx.matchOptions);
    if (cached) return cached;
    if (ctx.fallback) return ctx.fallback();
    throw e;
  }
}

// ───────────────────────── the factory ─────────────────────────

/**
 * Declarative one-call factory for the simple "one shell, one strategy" case
 * (used by Weather + FlightCheck). For multi-strategy / multi-cache SWs, compose
 * the primitives above in a slim sw.js instead. See JSDoc-by-knob below.
 */
export function createServiceWorker(config) {
  const scope = config.scope || self;
  const {
    cacheName: CACHE,
    shell = [],
    cdn = [],
    cdnHosts = [],
    bypassPrefixes = [],
    shellExtensions = null,
    cacheWhen = 'listed',
    installMode = 'all-or-nothing',
    fetchInit,
    navigateFallback = null,
    matchOptions,
    notifyOnActivate = null,
    cachePrunePrefix = null,
    skipWaiting = true,
    clientsClaim = true,
  } = config;

  if (!CACHE) throw new Error('createServiceWorker: config.cacheName is required');

  const shellPathSet = resolveShellPaths(shell, scope.location);
  const routeConfig = {
    origin: scope.location.origin,
    bypassPrefixes,
    cdnHosts: new Set(cdnHosts),
    shellExtensions,
  };

  async function onInstall() {
    const cache = await scope.caches.open(CACHE);
    if (installMode === 'best-effort') {
      await Promise.all(shell.map((url) =>
        scope.fetch(url, fetchInit)
          .then((res) => res.ok && cache.put(url, res))
          .catch(() => {})));
    } else {
      const tasks = [cache.addAll(shell)];
      for (const req of cdn) tasks.push(Promise.resolve(cache.add(req)).catch(() => {}));
      await Promise.all(tasks);
    }
    if (skipWaiting) await scope.skipWaiting();
  }

  async function onActivate() {
    await pruneCaches(scope, CACHE, cachePrunePrefix);
    if (clientsClaim) await claimClients(scope);
    if (notifyOnActivate) await notifyClients(scope, notifyOnActivate);
  }

  async function serveCdn(request) {
    const hit = await scope.caches.match(request);
    if (hit) return hit;
    const res = await scope.fetch(request);
    if (res.ok) {
      const copy = res.clone();
      scope.caches.open(CACHE).then((cache) => cache.put(request, copy)).catch(() => {});
    }
    return res;
  }

  async function serveShell(request, url) {
    try {
      const res = await scope.fetch(request, fetchInit);
      if (shouldCacheResponse(url, res, cacheWhen, shellPathSet)) {
        const copy = res.clone();
        scope.caches.open(CACHE).then((cache) => cache.put(request, copy)).catch(() => {});
      }
      return res;
    } catch (err) {
      const cached = await scope.caches.match(request, matchOptions);
      if (cached) return cached;
      if (navigateFallback && request.mode === 'navigate') {
        const fallback = await scope.caches.match(navigateFallback, matchOptions);
        if (fallback) return fallback;
      }
      throw err;
    }
  }

  function onFetch(event) {
    const request = event.request;
    if (request.method !== 'GET') return;
    let url;
    try { url = new URL(request.url); } catch { return; }
    const route = routeRequest(url, request, routeConfig);
    if (route === 'bypass') return;
    if (route === 'cdn') { event.respondWith(serveCdn(request)); return; }
    event.respondWith(serveShell(request, url));
  }

  scope.addEventListener('install', (event) => event.waitUntil(onInstall()));
  scope.addEventListener('activate', (event) => event.waitUntil(onActivate()));
  scope.addEventListener('fetch', onFetch);
}
