// @jfs/pwa-kit — shared service-worker primitives for the JFS family of
// buildless static PWAs.
//
// Eight sibling apps vendor this file (Weather, FlightCheck, BearsMockDraft,
// Surf-Tracker, John's News, Art-Gallery, market-monitor, JFS-Sports), and
// each of them used to hand-roll the same service worker: a version-keyed
// cache name, an app-shell precache list, install/activate/old-cache eviction,
// and some mix of network-first / cache-first / stale-while-revalidate /
// timeout-raced fetch strategies. Each one re-derived that logic slightly
// differently, and the family's #1 recurring bug — returning visitors stuck on
// a stale cached shell because someone forgot to bump the version — lives
// right here. This module is the single, tested copy of that logic.
//
// Pure ESM, dependency-free. Four layers:
//   1. Composable PRIMITIVES — lifecycle helpers (precache, pruneCaches,
//      claimClients, notifyClients, onSkipWaiting), predicates/helpers
//      (makeCacheable, safeCachePut, trimCache, offlineResponse,
//      stripQueryParams), and strategy functions (cacheFirst, networkFirst,
//      staleWhileRevalidate, networkFirstWithTimeout). Apps with bespoke
//      routing compose these in a slim sw.js.
//   2. createServiceWorker(config) — a declarative one-call factory for the
//      simple "one shell, one strategy" case, built on the primitives above.
//   3. registerServiceWorker(options) — the PAGE-side counterpart: register
//      sw.js and fire an injected onUpdate callback on a real upgrade. Runs in
//      the page, not the worker (guards on navigator.serviceWorker).
//   4. The update UX, also page-side — showUpdatePrompt (the tap-to-refresh
//      pill), applyUpdateAndReload (its tap action) and
//      registerWithUpdatePrompt (registration + pill, family defaults).
//
// v0.2.0 is a backward-compatible superset of v0.1.0 (the createServiceWorker
// factory + its pure helpers are unchanged in behavior). v0.4.0 adds the
// page-side registerServiceWorker (additive; the worker-scope API is
// unchanged). v0.4.1 hardens it: with waitForLoad, register immediately when
// the page has already loaded rather than waiting for a `load` that won't fire.
// v0.4.2: also announce a worker already `waiting` from a prior visit (an
// update that installed last session but never got surfaced), and tolerate
// register() resolving with no registration.
// v0.6.0 adds the family's standard update UX (additive): showUpdatePrompt
// (the tap-to-refresh pill), applyUpdateAndReload (its tap action, for both
// worker contracts — install-time skipWaiting AND waiting+SKIP_WAITING), and
// registerWithUpdatePrompt (registerServiceWorker preconfigured with the
// family policy: never auto-reload, show the pill, updateViaCache 'none',
// re-check on foreground).
// v0.6.1 hardens the factory: the offline shell fallback (and
// navigateFallback) look up only the app's OWN cache — never a co-hosted
// sibling's — matching serveCdn's existing scoping, and best-effort installs
// now precache the `cdn` list too (previously silently dropped).
// v0.6.2: an empty `cachePrunePrefix` / `cachePrefix` is ignored instead of
// honored (one spelling pruned every cache on the origin, the other none).
// v0.6.3: best-effort installs cache through the runtime path's predicate;
// registerServiceWorker also announces an active worker that is not the
// page's controller.
// v0.7.0: `clientsClaim` defaults to false; networkFirstWithTimeout clears its
// race timer; registerServiceWorker returns a { stop() } handle.
// v0.8.0 corrects the update model this file used to describe. Install-time
// skipWaiting — still the factory DEFAULT, so that no consumer's update model
// changes under an unreviewed pin bump — does NOT leave the open page on its
// old worker: activation hands every page the registration controls to the
// new one (see createServiceWorker's skipWaiting note). The compliant setting
// is `skipWaiting: false`, and the factory now wires the SKIP_WAITING message
// handler for it; its activate skips the prune while a NEWER worker is
// installing or waiting. The pill's tap resolves the waiting worker at TAP
// time (registration.waiting — threaded in by registerWithUpdatePrompt, else
// read via getRegistration()), shows "Updating…", and reloads on
// controllerchange, on that worker turning redundant, or at a 20 s ceiling
// (`ceilingMs`) — no longer blind after 800 ms. Additive: every export and
// call signature keeps working.
//
// Because a classic service worker can't `import` an ESM module, each app
// vendors a classic-global build of this file (generated by the kit's own
// vendor CLI — the `jfs-pwa-kit-vendor` bin, a shim over @jfs/vendor-cli —
// exposing `self.PWAKit`) and loads it with `importScripts(...)`. Tests
// import this ESM source directly.

// ───────────────────────── pure helpers ─────────────────────────

/** Build the versioned cache name. Keeping the version in the key is what makes
 *  an old deploy's cache get evicted on activate — bump the version, get a
 *  clean cache. */
export function cacheName(prefix, version) {
  return `${prefix}-${version}`;
}

/** Derive an app's cache-name PREFIX from one of its versioned cache names —
 *  the portion before the version separator, kept WITH its trailing separator
 *  so a startsWith() scope can't bleed into a sibling whose name merely shares
 *  a leading substring (`myapp-` won't match `myapp2-v1`). Used to scope pruning
 *  to the app's own caches on a shared origin (e.g. several family apps under
 *  `username.github.io`), so one app's activate can't wipe another's shell.
 *  `myapp-2` → `myapp-`; `mm-shell-v42` → `mm-shell-`; a name with no separator
 *  is returned unchanged.
 *
 *  CAVEAT: this splits on the LAST `-`, so it is only correct when the version
 *  segment contains no `-`. A hyphenated version (semver prerelease/build, e.g.
 *  `app-1.2.3-rc.1`) would derive `app-1.2.3-` and fail to match the app's own
 *  prior caches (`app-1.2.2`), leaving them un-pruned. Apps whose version may
 *  contain `-` MUST pass `cachePrefix` to the factory (or an explicit
 *  `cachePrunePrefix`) rather than rely on this heuristic. */
export function cacheNamePrefix(name) {
  if (!name) return name;
  const i = name.lastIndexOf('-');
  return i === -1 ? name : name.slice(0, i + 1);
}

/** Resolve a shell list (which may contain relative paths like './' or
 *  'css/style.css') to a Set of absolute pathnames, against the SW's own
 *  location. */
export function resolveShellPaths(shell, base) {
  return new Set(shell.map((p) => new URL(p, base).pathname));
}

/** Given the existing CacheStorage keys, return the ones to delete on activate.
 *  `keep` may be a single name, or an array/Set of names to retain (apps with
 *  several buckets — shell/runtime/api, or shell + an unversioned image cache).
 *  With `prefix`, only keys with that prefix are eligible for pruning, so
 *  co-hosted apps on the same origin don't wipe each other. */
export function staleCacheKeys(keys, keep, prefix) {
  const keepSet = keep instanceof Set ? keep : new Set(Array.isArray(keep) ? keep : [keep]);
  return keys.filter((k) => !keepSet.has(k) && (prefix ? k.startsWith(prefix) : true));
}

/** Build a response-cacheability predicate.
 *    allowOpaque      — accept opaque cross-origin responses (status 0). Needed
 *                       for no-cors images; off by default since an opaque body
 *                       can't be inspected for staleness.
 *    requireBasic     — only same-origin ('basic') responses.
 *    allowRedirected  — when false, reject res.redirected (can't trust the URL).
 *    status           — require an exact status (e.g. 200), excluding other 2xx.
 *  The default predicate is simply `res.ok`.
 *
 *  NOTE this defaults `allowRedirected` TRUE while `shouldCacheResponse`
 *  defaults it FALSE, and the divergence is deliberate rather than an
 *  oversight. `shouldCacheResponse` gates the SHELL path, where the cache key
 *  is a path out of a fixed precache list and a same-origin open-redirect
 *  could land a foreign body under it. This builds a predicate for arbitrary
 *  RUNTIME caching, where the key is whatever request the app itself chose to
 *  make and following a redirect is ordinary (a museum image CDN, an API
 *  edge). Flipping it here would silently stop caching redirected responses
 *  for every caller that never opted in. Pass `allowRedirected: false`
 *  explicitly where the stricter gate is wanted, as market-monitor does. */
export function makeCacheable(opts = {}) {
  const { allowOpaque = false, requireBasic = false, allowRedirected = true, status = null } = opts;
  return (res) => {
    if (!res) return false;
    if (res.type === 'opaque') return allowOpaque;
    if (!res.ok) return false;
    if (requireBasic && res.type !== 'basic') return false;
    if (!allowRedirected && res.redirected) return false;
    if (status != null && res.status !== status) return false;
    return true;
  };
}
const defaultCacheable = (res) => !!res && res.ok;

/** cache.put can reject when the origin's storage quota is exhausted. These are
 *  best-effort background writes, so swallow the failure rather than leak an
 *  unhandled rejection. */
export function safeCachePut(cache, request, response) {
  return cache.put(request, response).catch(() => {});
}

/** FIFO eviction: Cache.keys() returns entries in insertion order, so deleting
 *  from the front drops the least-recently-added entries first. Cheap and good
 *  enough for an immutable-asset cache (e.g. museum images) — no LRU bookkeeping. */
export async function trimCache(cache, max) {
  const keys = await cache.keys();
  if (keys.length <= max) return;
  for (let i = 0; i < keys.length - max; i++) {
    await cache.delete(keys[i]).catch(() => {});
  }
}

/** A deterministic offline fallback Response (default: 503 text/html) for when
 *  both network and cache miss, so respondWith never resolves to undefined. */
export function offlineResponse(body, init = {}) {
  return new Response(body, {
    status: init.status || 503,
    statusText: init.statusText || 'Service Unavailable',
    headers: init.headers || { 'Content-Type': 'text/html; charset=utf-8' },
  });
}

/** Return a request with the given query params stripped, for a stable cache
 *  key (e.g. dropping a `?cb=<timestamp>` buster). The outbound request is
 *  untouched — only the key used for cache lookup/write changes. Falls back to
 *  the original request if a Request can't be reconstructed. */
export function stripQueryParams(request, params, RequestCtor) {
  let url;
  try { url = new URL(request.url); } catch { return request; }
  let changed = false;
  for (const p of params) {
    if (url.searchParams.has(p)) { url.searchParams.delete(p); changed = true; }
  }
  if (!changed) return request;
  const Ctor = RequestCtor || (typeof Request !== 'undefined' ? Request : null);
  if (!Ctor) return request;
  try {
    return new Ctor(url.toString(), { method: request.method, headers: request.headers });
  } catch {
    return request;
  }
}

/** Decide how a GET should be handled: 'bypass' | 'cdn' | 'shell'. See the
 *  config knobs on createServiceWorker. */
export function routeRequest(url, request, config) {
  const cdnHosts = config.cdnHosts instanceof Set
    ? config.cdnHosts
    : new Set(config.cdnHosts || []);
  if (config.bypassPrefixes && config.bypassPrefixes.some((p) => url.pathname.startsWith(p))) {
    return 'bypass';
  }
  if (cdnHosts.has(url.hostname)) return 'cdn';
  if (url.origin !== config.origin) return 'bypass';
  const navigate = request && request.mode === 'navigate';
  const exts = config.shellExtensions;
  if (exts && exts.length) {
    if (navigate || exts.some((e) => url.pathname.endsWith(e))) return 'shell';
    return 'bypass';
  }
  return 'shell';
}

/** Decide whether a successful shell response may enter the cache.
 *    'listed'      — only paths in the precache shell set (bounded cache) AND a
 *                    same-origin ('basic') response, so a same-origin
 *                    open-redirect can't land a foreign body under a shell path.
 *    'shellRouted' — any same-origin ('basic') ok response routed as shell.
 *  `opts.allowRedirected` (default false) — reject `response.redirected` unless
 *  opted back in; a redirected response's URL can't be trusted as the cache key. */
export function shouldCacheResponse(url, response, mode, shellPathSet, opts = {}) {
  const { allowRedirected = false } = opts;
  if (!response || !response.ok) return false;
  if (!allowRedirected && response.redirected) return false;
  if (mode === 'listed') return response.type === 'basic' && shellPathSet.has(url.pathname);
  return response.type === 'basic';
}

// ───────────────────────── lifecycle primitives ─────────────────────────

/** Precache a shell list into `cacheName`.
 *    mode 'all-or-nothing' — cache.addAll: a single 404 aborts install (use
 *                            when a broken shell should fail the install).
 *    mode 'best-effort'    — individual adds via allSettled: whatever resolves
 *                            is cached, a stray miss just isn't available offline.
 *  `requestInit` (e.g. { cache: 'reload' }) bypasses the HTTP cache so a freshly
 *  bumped build never pre-caches the previous version's bytes. */
export async function precache(scope, name, assets, opts = {}) {
  const { mode = 'all-or-nothing', requestInit } = opts;
  const cache = await scope.caches.open(name);
  const list = assets || [];
  const req = (u) => (requestInit ? new Request(u, requestInit) : u);
  if (mode === 'best-effort') {
    await Promise.allSettled(list.map((u) => cache.add(req(u))));
  } else {
    await cache.addAll(list.map(req));
  }
}

/** Delete stale caches on activate. `keep` is a name or array/Set of names. */
export async function pruneCaches(scope, keep, prefix) {
  const keys = await scope.caches.keys();
  await Promise.all(staleCacheKeys(keys, keep, prefix).map((k) => scope.caches.delete(k)));
}

/** Take control of already-open pages. NOTE: some apps deliberately skip this
 *  (Art-Gallery) because claiming fires controllerchange and, paired with a
 *  reload-on-controllerchange, can loop on iOS Safari — only call it when the
 *  app wants the new worker to control the current page immediately. */
export async function claimClients(scope) {
  await scope.clients.claim();
}

/** Post a message (e.g. { type: 'SW_UPDATED' }) to controlled clients. */
export async function notifyClients(scope, message, matchOptions) {
  const clients = await scope.clients.matchAll(matchOptions || { type: 'window', includeUncontrolled: true });
  for (const c of clients) c.postMessage(message);
}

/** Wire a `message` listener that calls skipWaiting() when the page posts
 *  { type } (default 'SKIP_WAITING') — lets the page nudge a waiting worker
 *  into immediate activation after a deploy (the pill's tap). The waiting
 *  worker's half of the family update model: createServiceWorker wires it
 *  itself when `skipWaiting` is false, and a sw.js that calls it as well is
 *  unharmed — a second skipWaiting() on the same message is a no-op. */
export function onSkipWaiting(scope, type = 'SKIP_WAITING') {
  scope.addEventListener('message', (event) => {
    if (event.data && event.data.type === type) scope.skipWaiting();
  });
}

// ───────────────────────── strategy primitives ─────────────────────────
//
// Each strategy takes (request, ctx). ctx:
//   scope        — the SW global (provides caches, fetch, setTimeout)
//   cacheName    — bucket to read/write
//   isCacheable  — predicate (default res.ok); build with makeCacheable()
//   cacheKey     — key to read/write under (default: request) — for stripped keys
//   matchOptions — CacheQueryOptions for lookups (e.g. { ignoreSearch: true })
//   fallback     — () => Response used when network+cache both miss
//   timeoutMs    — (networkFirstWithTimeout only) ms before falling back to cache

/** Serve from cache, hit the network only on a miss. For immutable, versioned
 *  shell assets. */
export async function cacheFirst(request, ctx) {
  const cache = await ctx.scope.caches.open(ctx.cacheName);
  const key = ctx.cacheKey || request;
  const cached = await cache.match(key, ctx.matchOptions);
  if (cached) return cached;
  const res = await ctx.scope.fetch(request);
  if ((ctx.isCacheable || defaultCacheable)(res)) safeCachePut(cache, key, res.clone());
  return res;
}

/** Fetch fresh, fall back to cache (then optional offline fallback). For assets
 *  that carry shipped changes — always pick up the latest deploy when online. */
export async function networkFirst(request, ctx) {
  const cache = await ctx.scope.caches.open(ctx.cacheName);
  const key = ctx.cacheKey || request;
  try {
    const res = await ctx.scope.fetch(request);
    if ((ctx.isCacheable || defaultCacheable)(res)) safeCachePut(cache, key, res.clone());
    return res;
  } catch (err) {
    const cached = await cache.match(key, ctx.matchOptions);
    if (cached) return cached;
    if (ctx.fallback) return ctx.fallback();
    throw err;
  }
}

/** Serve the cached copy immediately and refresh it in the background, so the
 *  *next* load is current. For data that changes out-of-band and doesn't ride
 *  the app's version bump. */
export async function staleWhileRevalidate(request, ctx) {
  const cache = await ctx.scope.caches.open(ctx.cacheName);
  const key = ctx.cacheKey || request;
  const cached = await cache.match(key, ctx.matchOptions);
  const revalidate = ctx.scope.fetch(request).then((res) => {
    if ((ctx.isCacheable || defaultCacheable)(res)) safeCachePut(cache, key, res.clone());
    return res;
  });
  if (cached) {
    revalidate.catch(() => {}); // background refresh; ignore offline failures
    return cached;
  }
  return ctx.fallback ? revalidate.catch(() => ctx.fallback()) : revalidate;
}

/** Network-first, but if the network hasn't replied within `timeoutMs`, fall
 *  back to the last cached copy while the network fetch keeps running and
 *  refreshes the cache for the next tick. A pre-timeout 5xx also prefers a good
 *  cached copy over surfacing a transient server error. */
export async function networkFirstWithTimeout(request, ctx) {
  const cache = await ctx.scope.caches.open(ctx.cacheName);
  const key = ctx.cacheKey || request;
  const isCacheable = ctx.isCacheable || defaultCacheable;
  let settled = false;

  const network = ctx.scope.fetch(request).then(async (resp) => {
    settled = true;
    if (isCacheable(resp)) { try { await cache.put(key, resp.clone()); } catch { /* quota */ } }
    return resp;
  });

  // Keep the timer id so a network that wins the race can cancel it. Without
  // this every request armed a timer that outlived its own answer and then
  // woke the worker for a pointless cache.match — one per request, and a
  // service worker is kept alive by its pending timers.
  let timer = null;
  const timed = new Promise((resolve) => {
    timer = ctx.scope.setTimeout(async () => {
      if (settled) return;
      const cached = await cache.match(key, ctx.matchOptions);
      if (cached) resolve(cached);
    }, ctx.timeoutMs);
  });
  // Guarded: a scope is dependency-injected, and the hand-built fake scopes in
  // this kit's consumers' suites supply setTimeout without its counterpart.
  const clearTimer = () => {
    if (timer != null && ctx.scope && typeof ctx.scope.clearTimeout === 'function') {
      ctx.scope.clearTimeout(timer);
    }
  };

  try {
    const raced = (await Promise.race([network, timed])) || network;
    if (raced && raced.status >= 500) {
      const cached = await cache.match(key, ctx.matchOptions);
      if (cached) return cached;
    }
    return raced;
  } catch (e) {
    const cached = await cache.match(key, ctx.matchOptions);
    if (cached) return cached;
    if (ctx.fallback) return ctx.fallback();
    throw e;
  } finally {
    clearTimer();
  }
}

// ───────────────────────── the factory ─────────────────────────

/**
 * Declarative one-call factory for the simple "one shell, one strategy" case
 * (used by Weather, FlightCheck, BearsMockDraft, Surf-Tracker and John's
 * News). For multi-strategy / multi-cache SWs, compose the primitives above in
 * a slim sw.js instead. See JSDoc-by-knob below; for the update model, the
 * `skipWaiting` note — pass `skipWaiting: false`.
 */
export function createServiceWorker(config) {
  const scope = config.scope || self;
  const {
    cacheName: CACHE,
    shell = [],
    cdn = [],
    cdnHosts = [],
    bypassPrefixes = [],
    shellExtensions = null,
    cacheWhen = 'listed',
    installMode = 'all-or-nothing',
    fetchInit,
    navigateFallback = null,
    matchOptions,
    notifyOnActivate = null,
    cachePrunePrefix = null,
    cachePrefix = null,
    allowRedirected = false,
    // skipWaiting: TRUE by default — and `true` does NOT meet the family's
    // Service-worker-updates convention (a new build is never applied under
    // a reader mid-session). This comment used to call "skipWaiting on, claim
    // off" that convention, on the belief that a worker which activates at
    // install but never clients.claim()s "never seizes the page that is
    // already open". It does seize it. The SW spec's Activate algorithm hands
    // every client ALREADY controlled by the registration to the newly active
    // worker and fires controllerchange there; clients.claim() only concerns
    // clients that are not controlled yet. market-monitor measured it in
    // Chromium on 2026-09-30 (its PR #449): install-time skipWaiting swapped
    // the open page's controller and fired controllerchange, the activate
    // prune deleted the shell bucket that page had booted from, and its next
    // lazy import came from the NEW build, linked against the OLD build's
    // already-loaded modules.
    //
    // The compliant setting is `skipWaiting: false`: the new worker WAITS, the
    // open page keeps its worker and its bucket, and the pill's tap posts
    // SKIP_WAITING — answered by the handler wired at the bottom of this
    // factory, so there is nothing else to add — and reloads once the new
    // worker controls the page. New code and every migration should pass it.
    //
    // It stays the default ONLY so that no consumer is switched silently. This
    // file reaches eight apps through an automated weekly pin bump that
    // merges without review, and flipping the default would change every
    // factory consumer's update model at once with nobody checking its pill:
    // a pill that just reloads (an `onTap` of location.reload()) paired with
    // a worker that now waits never activates the new build — a single-tab
    // reload does not activate a waiting worker — so its updates would
    // strand. Each app moves by passing `skipWaiting: false` itself, with its
    // pill checked in the same change.
    skipWaiting = true,
    // clientsClaim: FALSE by default. Claiming takes control of the pages no
    // worker controls yet (a first visit) and fires controllerchange there —
    // with a reload-on-controllerchange, the historic iOS refresh loop. It
    // defaulted to true until v0.7.0, and the divergence was invisible: every
    // factory consumer (BearsMockDraft, FlightCheck, Weather, Surf-Tracker,
    // John's News) passes `clientsClaim: false` by hand, so nothing
    // exercised the default.
    clientsClaim = false,
  } = config;

  if (!CACHE) throw new Error('createServiceWorker: config.cacheName is required');

  const shellPathSet = resolveShellPaths(shell, scope.location);
  const routeConfig = {
    origin: scope.location.origin,
    bypassPrefixes,
    cdnHosts: new Set(cdnHosts),
    shellExtensions,
  };

  async function onInstall() {
    const cache = await scope.caches.open(CACHE);
    if (installMode === 'best-effort') {
      await Promise.all([
        ...shell.map((url) =>
          scope.fetch(url, fetchInit)
            // The same predicate the runtime path applies: `res.ok` alone let
            // a shell entry that 302s (an auth wall, a CDN edge redirect) be
            // cached under its ORIGINAL path at install, and every later
            // cache-fallback served it. The all-or-nothing branch's
            // cache.addAll refuses redirects itself, so the two install modes
            // disagreed on a security property.
            .then((res) => shouldCacheResponse(
              new URL(url, scope.location.href), res, 'shellRouted', shellPathSet, { allowRedirected },
            ) && cache.put(url, res))
            .catch(() => {})),
        // `cdn` entries are precached best-effort in BOTH install modes (they
        // were previously dropped here, so a best-effort app's CDN assets only
        // entered the cache on first runtime fetch — never offline-first).
        ...cdn.map((req) => Promise.resolve(cache.add(req)).catch(() => {})),
      ]);
    } else {
      const tasks = [cache.addAll(shell)];
      for (const req of cdn) tasks.push(Promise.resolve(cache.add(req)).catch(() => {}));
      await Promise.all(tasks);
    }
    if (skipWaiting) await scope.skipWaiting();
  }

  async function onActivate() {
    // Prefix-scoped by DEFAULT so pruning only ever deletes this app's caches —
    // a co-hosted sibling app's caches on the same origin are left untouched.
    // Precedence: an explicit cachePrunePrefix wins; else the app's own
    // `cachePrefix` (robust — works even when the version contains a `-`);
    // else fall back to deriving it from CACHE via the last-`-` heuristic
    // (correct only when the version has no `-`; see cacheNamePrefix caveat).
    //
    // Each step requires a NON-EMPTY STRING. An empty string is the obvious way
    // an app tries to spell "don't scope the prune", and both spellings misfire:
    // `cachePrunePrefix: ''` reaches staleCacheKeys' unscoped branch and deletes
    // EVERY other cache on the origin — a co-hosted sibling app's shell included,
    // the regression the prefix scoping exists to prevent — while
    // `cachePrefix: ''` derives the prefix `'-'`, which matches nothing, so every
    // past version's cache accumulates until quota. Neither is honored: an empty
    // (or non-string) value is ignored and the chain falls through.
    const usable = (v) => typeof v === 'string' && v !== '';
    const prunePrefix = usable(cachePrunePrefix)
      ? cachePrunePrefix
      : usable(cachePrefix)
        ? (cachePrefix.endsWith('-') ? cachePrefix : `${cachePrefix}-`)
        : cacheNamePrefix(CACHE);
    // No prune while a NEWER worker is installing or waiting: the prune keeps
    // only this build's bucket, so it would delete that worker's bucket out
    // from under it, and the newest build would later activate with an empty
    // shell. The tap makes this ordinary rather than exotic — SKIP_WAITING can
    // activate this worker while the next deploy is still installing.
    // Measured in market-monitor's e2e harness: a tap during the second
    // install left the newest worker `installed` with no shell bucket at all.
    // The newer worker's own activate prunes instead (worst case, an older
    // bucket outlives one activation). `scope.registration` is guarded: a
    // hand-built test scope — this kit's and its consumers' — carries none.
    const reg = scope.registration;
    const newerWorker = !!(reg && (reg.installing || reg.waiting));
    if (!newerWorker) await pruneCaches(scope, CACHE, prunePrefix);
    if (clientsClaim) await claimClients(scope);
    if (notifyOnActivate) await notifyClients(scope, notifyOnActivate);
  }

  async function serveCdn(request) {
    // Scope the lookup to this app's own CDN bucket. A bare
    // scope.caches.match(request) searches EVERY cache on the origin and could
    // return a sibling app's — or an older version's — entry for the same URL.
    const cache = await scope.caches.open(CACHE);
    const hit = await cache.match(request);
    if (hit) return hit;
    const res = await scope.fetch(request);
    if (res.ok) {
      const copy = res.clone();
      safeCachePut(cache, request, copy);
    }
    return res;
  }

  async function serveShell(request, url) {
    try {
      const res = await scope.fetch(request, fetchInit);
      if (shouldCacheResponse(url, res, cacheWhen, shellPathSet, { allowRedirected })) {
        const copy = res.clone();
        scope.caches.open(CACHE).then((cache) => cache.put(request, copy)).catch(() => {});
      }
      return res;
    } catch (err) {
      // Offline fallback scoped to this app's OWN bucket (same reasoning as
      // serveCdn): a bare scope.caches.match() searches every cache on the
      // origin and could serve a co-hosted sibling app's — or a stale
      // un-pruned version's — entry for the same URL.
      const cache = await scope.caches.open(CACHE);
      const cached = await cache.match(request, matchOptions);
      if (cached) return cached;
      if (navigateFallback && request.mode === 'navigate') {
        const fallback = await cache.match(navigateFallback, matchOptions);
        if (fallback) return fallback;
      }
      throw err;
    }
  }

  function onFetch(event) {
    const request = event.request;
    if (request.method !== 'GET') return;
    let url;
    try { url = new URL(request.url); } catch { return; }
    const route = routeRequest(url, request, routeConfig);
    if (route === 'bypass') return;
    if (route === 'cdn') { event.respondWith(serveCdn(request)); return; }
    event.respondWith(serveShell(request, url));
  }

  scope.addEventListener('install', (event) => event.waitUntil(onInstall()));
  scope.addEventListener('activate', (event) => event.waitUntil(onActivate()));
  scope.addEventListener('fetch', onFetch);
  // A worker that waits needs something to answer the pill's SKIP_WAITING —
  // without it the tap posts into the void and the update strands until every
  // window has closed. Wired here so `skipWaiting: false` works with no extra
  // line in sw.js. A sw.js that ALSO calls onSkipWaiting(self) gets a second
  // listener, and that is harmless: skipWaiting() sets the worker's
  // skip-waiting flag and runs the spec's Try Activate, which returns at once
  // when the worker is no longer waiting or is already activating — so the
  // second call on the same message does nothing more than the first.
  if (!skipWaiting) onSkipWaiting(scope);
}

// ───────────────────── page side (registration) ─────────────────────

// The counterpart to everything above: the code that runs on the PAGE (not in
// the worker) to register `sw.js` and detect an upgrade. Every sibling app
// hand-rolls the same shape — register, watch `installing`, and when a worker
// reaches `installed` while one is ALREADY controlling the page (a real
// upgrade, not the first install), tell the app so it can prompt a refresh.
// None auto-reload. What differs per app is only the notify step (a
// `sw-update-ready` CustomEvent, an inline "tap to refresh" pill, …) — that's
// the injected `onUpdate` callback here.
//
// The historic controllerchange refresh loop is impossible for one reason
// only: nothing in this kit reloads on controllerchange except the pill's tap,
// which binds a once-listener after the reader has asked for the update. This
// comment used to credit sw.js not calling clients.claim(), and that is not
// what prevents it: activating a new worker fires controllerchange on every
// page the registration already controls, claim or no claim (see
// createServiceWorker's skipWaiting note). An app that adds its own
// reload-on-controllerchange reopens the loop whatever its worker does.
//
// `scope` is dependency-injected (defaults to globalThis, i.e. window in a
// browser) so this is unit-testable without mocking globals, matching the rest
// of the kit.

/**
 * Register a service worker and invoke `onUpdate` when a NEW worker installs
 * over an already-controlling one (a real upgrade).
 *
 * @param {object} [options]
 * @param {object} [options.scope] window-like object (default globalThis) —
 *   must expose `navigator` and, for `waitForLoad`, `addEventListener`.
 * @param {string} [options.swUrl='sw.js'] path passed to register().
 * @param {object} [options.registerOptions] second arg to register()
 *   (e.g. `{ updateViaCache: 'none' }`, `{ scope: '/' }`).
 * @param {boolean} [options.waitForLoad=false] defer registration until the
 *   page's `load` event (some apps register on load, others immediately).
 * @param {(worker: object, registration: object) => void} [options.onUpdate]
 *   called once per real upgrade, with the freshly-installed worker + the
 *   registration.
 * @param {(err: any) => void} [options.onError] called if register() rejects
 *   (file:// / unsupported / dev server). Silent by default.
 * @param {boolean} [options.updateOnVisible=false] call registration.update()
 *   whenever the page returns to the foreground (visibilitychange → visible).
 *   iOS home-screen PWAs are suspended, not relaunched, when the user switches
 *   back — no navigation happens, so the browser never re-checks sw.js and an
 *   update can go unnoticed for days. update() is a no-op when the live worker
 *   is byte-identical, so foreground checks are cheap.
 * @param {number} [options.updateIntervalMs=0] additionally call
 *   registration.update() on this interval (0 = off) so long-lived visible
 *   sessions also notice a deploy.
 * @returns {{stop: () => void}} a handle whose `stop()` cancels the
 *   `updateIntervalMs` poll. Registration is async, so the interval may not be
 *   armed yet when the caller gets the handle — `stop()` covers both orders,
 *   and is a no-op when no interval was asked for. (The function returned
 *   `undefined` before, so the added shape breaks no caller.)
 */
export function registerServiceWorker(options = {}) {
  const {
    scope = typeof globalThis !== 'undefined' ? globalThis : undefined,
    swUrl = 'sw.js',
    registerOptions,
    waitForLoad = false,
    onUpdate,
    onError,
    updateOnVisible = false,
    updateIntervalMs = 0,
  } = options;

  // `stopped` is checked when the interval is finally armed, so a stop() that
  // lands before register() resolves still prevents the poll from starting.
  let intervalId = null;
  let stopped = false;
  const handle = {
    stop() {
      stopped = true;
      if (intervalId != null && scope && typeof scope.clearInterval === 'function') {
        scope.clearInterval(intervalId);
      }
      intervalId = null;
    },
  };

  const nav = scope && scope.navigator;
  if (!nav || !('serviceWorker' in nav)) return handle;

  const doRegister = () => {
    const p = registerOptions
      ? nav.serviceWorker.register(swUrl, registerOptions)
      : nav.serviceWorker.register(swUrl);
    p.then((reg) => {
      // Some environments (e.g. Playwright with serviceWorkers:'block') resolve
      // register() with no registration — bail before reading off undefined.
      if (!reg) return;
      const announce = (worker) => {
        if (typeof onUpdate === 'function') onUpdate(worker, reg);
      };
      const watch = (worker) => {
        if (!worker) return;
        worker.addEventListener('statechange', () => {
          // controller is null on the very first install — only announce an
          // upgrade when one was already controlling the page.
          if (worker.state === 'installed' && nav.serviceWorker.controller) {
            announce(worker);
          }
        });
      };
      // A new worker may already be installing when register() resolves, or show
      // up later via updatefound — cover both.
      watch(reg.installing);
      reg.addEventListener('updatefound', () => watch(reg.installing));
      // A new worker may ALSO have already installed on a PRIOR visit and be
      // sitting in `waiting` (the old worker still controls this page). Neither
      // `installing` nor `updatefound` covers that — announce it directly so an
      // update that's been ready since last time isn't silently stranded.
      if (reg.waiting && nav.serviceWorker.controller) announce(reg.waiting);
      // An ACTIVE worker that is not the one controlling this page is an
      // update too. This passage used to say that under the factory's default
      // contract (install-time skipWaiting, no claim) a new worker goes
      // installed → activated "while the OLD worker keeps controlling this
      // page". It does not: activation hands every page the registration
      // controls to the new worker and fires controllerchange there (see
      // createServiceWorker's skipWaiting note). Under that contract the
      // controller is normally reg.active itself by the time this runs, and
      // the check below catches only the moment before that controller change
      // reaches the page. So an update that installed AND activated before the
      // listeners above attached shows no pill at all under that contract,
      // with this page already running under the new worker. The waiting model
      // (`skipWaiting: false`) keeps it in reg.waiting — announced above —
      // until the tap.
      if (reg.active && nav.serviceWorker.controller && reg.active !== nav.serviceWorker.controller) {
        announce(reg.active);
      }
      // Proactive update checks. Browsers only re-check sw.js on navigation,
      // which a resumed iOS home-screen PWA never performs — so without these
      // the onUpdate prompt can lag a deploy by days.
      const checkForUpdate = () => {
        try {
          const up = reg.update();
          if (up && typeof up.catch === 'function') up.catch(() => {});
        } catch { /* update() unsupported — best-effort only */ }
      };
      const doc = scope && scope.document;
      if (updateOnVisible && doc && typeof doc.addEventListener === 'function') {
        doc.addEventListener('visibilitychange', () => {
          if (doc.visibilityState === 'visible') checkForUpdate();
        });
      }
      if (updateIntervalMs > 0 && !stopped && scope && typeof scope.setInterval === 'function') {
        intervalId = scope.setInterval(checkForUpdate, updateIntervalMs);
      }
    }).catch((err) => {
      if (typeof onError === 'function') onError(err);
    });
  };

  if (waitForLoad && scope && typeof scope.addEventListener === 'function') {
    // If the page has ALREADY finished loading (e.g. this module was imported
    // late, or dynamically), the `load` event won't fire again — registering on
    // it would wait forever. Register now in that case.
    if (scope.document && scope.document.readyState === 'complete') {
      doRegister();
    } else {
      scope.addEventListener('load', doRegister, { once: true });
    }
  } else {
    doRegister();
  }

  return handle;
}

// ───────────────────────── update prompt (tap to refresh) ─────────────────────────
// The family's standard "New version available — tap to refresh" pill,
// extracted from BearsMockDraft (js/sw-register.js) and Surf-Tracker
// (docs/js/18-sw.js), which each carried a byte-similar copy. Policy, by
// family decision: apps NEVER reload on their own — a deploy shows the pill
// and the user decides. This replaces both silent policies that used to
// coexist (JFS-Sports' immediate skipWaiting+reload, market-monitor's
// deferred hidden-tab reload).
//
// The pill is self-contained: styles are assigned via the CSSOM
// (style.cssText), which every strict family CSP allows (style-src governs
// markup, not CSSOM), so no app stylesheet or toast element is required.
//
// The tap meets two service-worker contracts in the family, and only one of
// them is compliant:
//   - waiting worker + SKIP_WAITING (createServiceWorker({ skipWaiting:
//     false }), or a sw.js that calls onSkipWaiting): the convention's
//     mechanism. The new build waits for the tap; the tap posts SKIP_WAITING
//     and reloads once the new worker controls the page. Reloading before
//     that would serve the OLD shell again (a single-tab reload never
//     activates a waiting worker on its own).
//   - install-time skipWaiting (still the factory's default): NOT compliant.
//     By tap time activation has already handed this page to the new worker
//     and pruned the bucket it booted from (createServiceWorker's skipWaiting
//     note); the tap's plain reload only brings the page's code up to the
//     worker it is already running under.
//
// applyUpdateAndReload serves both with one code path, decided at TAP time:
//   - Which worker: the registration's `waiting` worker — always the newest
//     installed build — falling back to the one the pill was created with.
//     The pill is created once per document and holds the worker from the
//     FIRST announce. After a second deploy installs before the tap, that
//     worker is `redundant`, a SKIP_WAITING posted at it goes nowhere, and the
//     old 800 ms fallback reloaded onto the OLD shell (measured in
//     market-monitor: a second tap was needed).
//   - A worker that is waiting: reload on controllerchange, when it turns
//     `redundant` (a newer install superseded it, or it failed to activate)
//     or reaches `activated`, or at a ceiling (UPDATE_CEILING_MS) — never
//     blind after 800 ms. A skip-waiting worker activates only once the active
//     worker has no fetch in flight, so a tap during any request slower than
//     800 ms reloaded onto the OLD build, and the new worker then took over
//     that fresh page and pruned its shell (measured in Chromium,
//     market-monitor, with one API request held 4 s). Meanwhile the pill reads
//     "Updating…" and is disabled, so a second tap arms nothing.
//   - A worker that already activated (install-time skipWaiting), a redundant
//     one with nothing newer waiting, or none: a plain reload, as before. One
//     still `activating` takes the waiting route: its controllerchange may
//     already have fired, and the `activated` statechange then reloads (once
//     a worker is activating, the spec always completes the activation).
// The controllerchange listener is bound only on tap, so the historic
// reload-on-controllerchange loop stays impossible.

/** How long a tap waits for the waiting worker to take control before it
 *  reloads anyway (applyUpdateAndReload's `ceilingMs`). A reload while that
 *  worker still waits serves the OLD shell, so this sits past any request an
 *  app plausibly holds open on the old worker — which is what made the 800 ms
 *  it replaces misfire. 20 s is market-monitor's measured choice: past its
 *  12–15 s client fetch bounds, so by then the page has given up on every
 *  request that could be holding the old worker busy. */
export const UPDATE_CEILING_MS = 20000;

/**
 * The pill's tap: activate the newest waiting worker and reload exactly once,
 * after it controls this page. Serves both worker contracts — see the section
 * comment above.
 *
 * @param {ServiceWorker|null} worker the worker the pill was created with —
 *   the fallback when the registration has nothing waiting.
 * @param {object} [scope=globalThis] window-like (`location`, `navigator`,
 *   `setTimeout`), injected so this is testable without global mocks.
 * @param {object} [options] (optional third argument; the two-argument
 *   call keeps working)
 * @param {ServiceWorkerRegistration|null} [options.registration] read at call
 *   time — its `waiting` worker wins over `worker`. Omitted, the tap asks
 *   `navigator.serviceWorker.getRegistration()` instead (where it exists).
 * @param {HTMLElement|null} [options.pill] set to "Updating…" and disabled
 *   while the tap waits for the new worker.
 * @param {number} [options.ceilingMs=UPDATE_CEILING_MS] reload anyway after
 *   this long if the waiting worker never takes control.
 */
export function applyUpdateAndReload(worker, scope = globalThis, options = {}) {
  const win = scope || globalThis;
  const opts = options || {};
  const pill = opts.pill || null;
  const ceilingMs = Number.isFinite(opts.ceilingMs) && opts.ceilingMs >= 0 ? opts.ceilingMs : UPDATE_CEILING_MS;
  let reloaded = false;
  const reload = () => {
    if (reloaded) return;
    reloaded = true;
    try { win.location.reload(); } catch { /* detached test window */ }
  };
  let container = null;
  try { container = (win.navigator && win.navigator.serviceWorker) || null; } catch { /* no navigator */ }

  const apply = (target) => {
    try {
      const state = target && target.state;
      // Nothing to wait for — see the section comment.
      if (!target || !container || state === 'activated' || state === 'redundant') {
        reload();
        return;
      }
      // A waiting worker: nudge it live, reload once it has taken over.
      container.addEventListener('controllerchange', reload, { once: true });
      if (typeof target.addEventListener === 'function') {
        target.addEventListener('statechange', () => {
          if (target.state === 'activated' || target.state === 'redundant') reload();
        });
      }
      if (pill) {
        try { pill.textContent = 'Updating…'; pill.disabled = true; } catch { /* a read-only stand-in */ }
      }
      const timed = typeof win.setTimeout === 'function';
      if (timed) win.setTimeout(reload, ceilingMs);
      try { target.postMessage({ type: 'SKIP_WAITING' }); } catch { /* no handler — the ceiling resolves the tap */ }
      // No timer to arm a ceiling with (a bare test window): reload now rather
      // than strand on "Updating…" — the one case that keeps the old behaviour.
      if (!timed) reload();
    } catch {
      reload();
    }
  };

  if (opts.registration) {
    let target = worker;
    try { target = opts.registration.waiting || worker; } catch { /* unreadable — use the held worker */ }
    apply(target);
    return;
  }
  let lookup = null;
  try {
    if (container && typeof container.getRegistration === 'function') lookup = container.getRegistration();
  } catch { /* no registration lookup — use the held worker */ }
  if (lookup && typeof lookup.then === 'function') {
    lookup.then((reg) => apply((reg && reg.waiting) || worker), () => apply(worker));
  } else {
    apply(worker);
  }
}

export const UPDATE_PROMPT_ID = 'swUpdatePrompt';

/**
 * Show the dismiss-less tap-to-refresh pill (idempotent per document by id).
 * @param {Object} [options]
 * @param {Document} [options.doc=globalThis.document]
 * @param {string} [options.label='New version available — tap to refresh']
 * @param {string} [options.id=UPDATE_PROMPT_ID]
 * @param {ServiceWorker|null} [options.worker] the freshly installed worker
 *   (from registerServiceWorker's onUpdate) — the tap's fallback
 * @param {ServiceWorkerRegistration|null} [options.registration] the
 *   registration (onUpdate's second argument): the tap reads its `waiting`
 *   worker at TAP time, so a deploy that lands after the pill appeared is the
 *   one applied. Without it the tap asks `getRegistration()` instead.
 * @param {number} [options.ceilingMs=UPDATE_CEILING_MS] how long the tap
 *   waits for the new worker to take control before reloading anyway
 * @param {Object} [options.style] cssText overrides merged over the default
 *   pill look, e.g. { background: '#0b162a', border: '1px solid #c83803' }
 * @param {(worker: ServiceWorker|null, registration: ServiceWorkerRegistration|null) => void} [options.onTap]
 *   replaces the default applyUpdateAndReload tap action (an override owns
 *   the whole tap: a waiting worker needs its SKIP_WAITING — a bare
 *   location.reload() never activates it)
 * @returns {HTMLElement|null} the pill (existing one when already shown)
 */
export function showUpdatePrompt(options = {}) {
  const doc = options.doc || (typeof globalThis.document !== 'undefined' ? globalThis.document : null);
  if (!doc || !doc.body) return null;
  const id = options.id || UPDATE_PROMPT_ID;
  const existing = doc.getElementById(id);
  if (existing) return existing;

  const btn = doc.createElement('button');
  btn.id = id;
  btn.type = 'button';
  btn.textContent = options.label || 'New version available — tap to refresh';

  const style = {
    position: 'fixed',
    left: '50%',
    bottom: 'calc(16px + env(safe-area-inset-bottom, 0px))',
    transform: 'translateX(-50%)',
    'z-index': '2147483647',
    'max-width': '92vw',
    padding: '12px 18px',
    font: '600 14px/1.2 system-ui,-apple-system,Segoe UI,Roboto,sans-serif',
    color: '#fff',
    background: '#1c2733',
    border: '1px solid #5aa9f5',
    'border-radius': '999px',
    'box-shadow': '0 6px 24px rgba(0,0,0,.45)',
    cursor: 'pointer',
    ...(options.style || {}),
  };
  btn.style.cssText = Object.entries(style).map(([k, v]) => `${k}:${v}`).join(';');

  const worker = options.worker || null;
  const registration = options.registration || null;
  let tapped = false;
  btn.addEventListener('click', () => {
    if (typeof options.onTap === 'function') { options.onTap(worker, registration); return; }
    // One tap arms the update. The pill is disabled once the tap waits, but
    // the worker lookup can be async, so a second tap in between must not arm
    // a second set of listeners.
    if (tapped) return;
    tapped = true;
    applyUpdateAndReload(worker, (doc.defaultView || globalThis), {
      registration,
      pill: btn,
      ceilingMs: options.ceilingMs,
    });
  });
  doc.body.appendChild(btn);
  return btn;
}

/**
 * registerServiceWorker preconfigured with the family update policy:
 * updateViaCache 'none', re-check on return to foreground, register after
 * `load`, and show the tap-to-refresh pill on a real upgrade (never
 * auto-reload). All registerServiceWorker options pass through and win over
 * the defaults; `prompt` carries showUpdatePrompt options (label/id/style/
 * ceilingMs/onTap). The registration is threaded into the pill, so its tap
 * applies whichever worker is waiting when it is tapped. An app-supplied
 * onUpdate runs IN ADDITION to the pill (e.g. to also surface a diagnostics
 * note). Returns registerServiceWorker's handle.
 */
export function registerWithUpdatePrompt(options = {}) {
  const { prompt, onUpdate, ...rest } = options;
  // Resolve the document off the registration scope so a custom scope
  // (tests, iframes) shows its pill in the right document.
  const doc = (prompt && prompt.doc)
    || (rest.scope && rest.scope.document)
    || (typeof globalThis.document !== 'undefined' ? globalThis.document : null);
  return registerServiceWorker({
    registerOptions: { updateViaCache: 'none' },
    updateOnVisible: true,
    waitForLoad: true,
    ...rest,
    onUpdate: (worker, reg) => {
      showUpdatePrompt({ ...(prompt || {}), doc, worker, registration: reg });
      if (typeof onUpdate === 'function') onUpdate(worker, reg);
    },
  });
}
